[project]
name = "don-botto"
version = "0.1.0"
description = "Kickbase Bot Manager"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
 "openai>=1.98.0",
 "pydantic>=2.11.7",
 "requests>=2.32.4",
]
